export enum UserTypes {
  GET_CURRENT_USER = "GET_CURRENT_USER",
  USER_LOADING = "USER_LOADING",
  SET_DATA_USER_REDUCER = "SET_DATA_USER_REDUCER",

  GET_ALLOWED_APP_LIST = "GET_ALLOWED_APP_LIST",

  GET_PERMISSIONS = "GET_PERMISSIONS",

  GET_HUB_LIST = "GET_HUB_LIST",
}

export enum MetaDataTypes {
  META_DATA_LOADING = "META_DATA_LOADING",
  SET_META_DATA_REDUCER = "SET_META_DATA_REDUCER",

  GET_HUB_ACTIONS = "GET_HUB_ACTIONS",

  GET_HUB_AREA_ACTIONS = "GET_HUB_AREA_ACTIONS",
}
