export enum UserTypes {
  GET_CURRENT_USER = "GET_CURRENT_USER",
  USER_LOADING = "USER_LOADING",
  SET_DATA_USER_REDUCER = "SET_DATA_USER_REDUCER",

  GET_ALLOWED_APP_LIST = "GET_ALLOWED_APP_LIST",
}

export enum MetaDataTypes {
  GET_TICKETS_STATUS_LIST = "GET_TICKETS_STATUS_LIST",

  GET_TICKETS_TYPE_LIST = "GET_TICKETS_TYPE_LIST",
  META_DATA_LOADING = "META_DATA_LOADING",
  SET_META_DATA_REDUCER = "SET_META_DATA_REDUCER",
}
