export enum UserTypes {
  GET_CURRENT_USER = "GET_CURRENT_USER",
  USER_LOADING = "USER_LOADING",
  SET_DATA_USER_REDUCER = "SET_DATA_USER_REDUCER",

  GET_ALLOWED_APP_LIST = "GET_ALLOWED_APP_LIST",

  GET_PERMISSIONS = "GET_PERMISSIONS",
}

export enum TicketTypes {
  GET_TICKETS_IN_PROCESS_LIST = "GET_TICKETS_IN_PROCESS_LIST",

  GET_TICKETS_PROCESSED_LIST = "GET_TICKETS_PROCESSED_LIST",
  TICKET_LOADING = "TICKET_LOADING",
  SET_DATA_TICKET_REDUCER = "SET_DATA_TICKET_REDUCER",

  UPDATE_EXPLANATION_TICKETS = "UPDATE_EXPLANATION_TICKETS",

  GET_TICKET_DETAIL = "GET_TICKET_DETAIL",

  GET_WORKFLOW_DETAIL = "GET_WORKFLOW_DETAIL",

  GET_ARREARS_TICKETS = "GET_ARREARS_TICKETS",

  GET_TICKETS_BACKLOG = "GET_TICKETS_BACKLOG",
  GET_TICKETS_COMPLAINT = "GET_TICKETS_COMPLAINT",

  GET_ASSIGNMENT_RATE_LIST = "GET_ASSIGNMENT_RATE_LIST",
}

export enum MetaDataTypes {
  GET_TICKETS_STATUS_LIST = "GET_TICKETS_STATUS_LIST",

  GET_TICKETS_TYPE_LIST = "GET_TICKETS_TYPE_LIST",
  META_DATA_LOADING = "META_DATA_LOADING",
  SET_META_DATA_REDUCER = "SET_META_DATA_REDUCER",

  GET_WAREHOUSE_LIST = "GET_WAREHOUSE_LIST",

  GET_ALL_WAREHOUSE_LIST = "GET_ALL_WAREHOUSE_LIST",

  GET_ISSUE_TYPES = "GET_ISSUE_TYPES",
}
